# Generated by Django 5.2.11 on 2026-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
